//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tst-gw-devwar04.test.hastings.local:9080/pc/ws/com/hastings/integration/ag" +
            "gs/privatecar/qcore/PCQuoteEngineAPI")]
        public string IslServices_WsQhDevWarr_PCQuoteEngineAPI {
            get {
                return ((string)(this["IslServices_WsQhDevWarr_PCQuoteEngineAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ad1-prd-islclus.network.uk.ad:8080/Isl.svc")]
        public string IslServices_WsIslPrd_Isl {
            get {
                return ((string)(this["IslServices_WsIslPrd_Isl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bx2-dev-is01.test.hastings.local:8080/Isl.svc")]
        public string IslServices_WsIslDevWarr_Isl {
            get {
                return ((string)(this["IslServices_WsIslDevWarr_Isl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tst-gw-devwar04.test.hastings.local:9080/pc/ws/com/hastings/integration/ag" +
            "gs/commercialvan/qcore/CVQuoteEngineAPI")]
        public string IslServices_VanQuoteServiceDevWarr_CVQuoteEngineAPI {
            get {
                return ((string)(this["IslServices_VanQuoteServiceDevWarr_CVQuoteEngineAPI"]));
            }
        }
    }
}
